services:
  html-server:
    image: html-server
    ports: 
      - 80:80
    expose: 
      - 80:80

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock