services:
  html-server:
    image: index.docker.io/crispydanger/lab4-5:main
    ports: 
      - "80:80"
    expose: 
      - "80"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 15